# DO NOT EDIT — generated by datamodel-codegen from openapi/openapi.json.
# Run `make gen` to regenerate. See openapi/openapi.json for the contract.

from __future__ import annotations

from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class UserId(RootModel[str]):
    root: Annotated[str, Field(max_length=255)]


class EventIn(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    event_id: Annotated[str, Field(max_length=255, min_length=1)]
    type: Annotated[str, Field(max_length=255, min_length=1)]
    user_id: UserId | None = None
    ts: AwareDatetime | None = None
    props: dict[str, Any] | None = None


class EventAccepted(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: str = "accepted"
    event_id: str


class MetricPoint(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    bucket: AwareDatetime
    count: int


class MetricsResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Annotated[
        str,
        Field(
            description=(
                "Event type filter applied. 'all' when no type filter was "
                "specified (aggregate across all types)."
            )
        ),
    ]
    interval: str
    from_: Annotated[AwareDatetime, Field(alias="from")]
    to: AwareDatetime
    series: list[MetricPoint]


class TopItem(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: str
    count: int


class TopResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    dimension: str
    from_: Annotated[AwareDatetime, Field(alias="from")]
    to: AwareDatetime
    items: list[TopItem]


class InfoResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    cloud_provider: str
    region: str
    version: str
    buffer: str


class HealthStatus(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: str


class Checks(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    redis: bool | None = None
    postgres: bool | None = None


class ReadyzResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: str
    checks: Checks


class ErrorBody(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: str
    message: str
    details: Any = None


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    error: ErrorBody
